### list posts
GET http://localhost:3000/posts

### create post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "describe": "Gato post",
  "imageUrl": "https://placecats.com/millie/300/150",
  "alt": "Gato fazendo um post"
}
